-- Workers/Labour seed data
INSERT INTO workers (name, daily_rate, active) VALUES
  ('Aarav Rajwar', 400, true),
  ('Abhay Karmali', 400, true),
  ('Abhiram', 400, true),
  ('AJ Sunil', 400, true),
  ('Ajay', 500, true),
  ('Ajay Balsagra', 400, true),
  ('Ajay Karmali', 450, true),
  ('Ajay Mahto', 400, true),
  ('Ajay Munda', 400, true),
  ('Ajay Rajwar', 450, true),
  ('Akash', 500, true),
  ('Akash Mahto', 400, true),
  ('Akshay Kumar', 400, true),
  ('Alok Karmali', 550, true),
  ('Altaf', 450, true),
  ('Amar', 450, true),
  ('Amar Rajwar', 400, true),
  ('Amit Karmali', 400, true),
  ('Amresh Marandi', 400, true),
  ('Amrit Rajwar', 400, true),
  ('Anand Kumar', 400, true),
  ('Anil Balsagra', 400, true),
  ('Anil Karmali', 400, true),
  ('Anil Kumar Saw', 500, true),
  ('Anil Rajwar', 400, true),
  ('Anil Ram', 400, true),
  ('Anjan Kumar', 400, true),
  ('Ankit KR Saw', 400, true),
  ('Ankit Verma', 400, true),
  ('Anuj kr Mahto', 400, true),
  ('Arjun Karmali', 400, true),
  ('Armesh Marandi', 400, true),
  ('Aryan', 500, true),
  ('Aryan Rajwanshi', 400, true),
  ('Ashish Kumar', 400, true),
  ('Ashok Karmali', 400, true),
  ('Ashok Nawada', 769, true),
  ('Ashok Usra', 400, true),
  ('Atul Raj', 450, true),
  ('Ayush Rajwar', 450, true),
  ('Azad', 550, true),
  ('Azad Karmali', 400, true),
  ('Bablu', 650, true),
  ('Bablu Katihar', 600, true),
  ('Bablu Kumar', 400, true),
  ('Bablu Mahto', 400, true),
  ('Bablu Rajwar', 400, true),
  ('Badal Karmali', 400, true),
  ('Bali', 500, true),
  ('Balkrishna Rajwar', 400, true),
  ('Balram carpenter', 600, true),
  ('Basant Munda', 400, true),
  ('Basudev Usra', 400, true),
  ('Bhim Welder', 500, true),
  ('Bhola katihar', 800, true),
  ('Bhola Rajwar', 400, true),
  ('Binod Balsagra', 400, true),
  ('Binod Rajwar', 500, true),
  ('Binod usra', 600, true),
  ('Chandan Kumar', 400, true),
  ('Chandra Sekhar', 450, true),
  ('Chhotu', 400, true),
  ('Deepak Katihar', 600, true),
  ('Deepak Kumar', 400, true),
  ('Deepak Soren', 400, true),
  ('Deepak Usra', 400, true),
  ('Devendra Mahto', 400, true),
  ('Devgan', 650, true),
  ('Dildar Painter', 500, true),
  ('Dilip Chaudhry', 700, true),
  ('Dilip filtter', 700, true),
  ('Dinesh Balsagra', 400, true),
  ('Dinesh Rajwar', 400, true),
  ('Diwakar Usra', 400, true),
  ('Dulal Rajwar', 500, true),
  ('Eklok', 550, true),
  ('Faizan', 550, true),
  ('Ganesh Fitter', 500, true),
  ('Gaurav Chakrabarti', 400, true),
  ('Gautam Mile', 400, true),
  ('Golu Kumar', 400, true),
  ('Gopal Katihar', 600, true),
  ('Goverdhan Rajwar', 400, true),
  ('Govind', 450, true),
  ('Govind carpenter', 600, true),
  ('Govind Rajwar', 400, true),
  ('Govind Soren', 450, true),
  ('Guddu Katihar', 600, true),
  ('Guddu Painter', 600, true),
  ('Guru Charan', 400, true),
  ('Haider Ali', 400, true),
  ('Harish Kumar', 400, true),
  ('Hemlal', 450, true),
  ('Horil', 550, true),
  ('Irshad painter', 800, true),
  ('Jaggu', 500, true),
  ('Jayant Kumar Mahto', 400, true),
  ('Jeetu Rajwar', 400, true),
  ('Jeevan Fitter', 500, true),
  ('Jeevan Karmali', 400, true),
  ('Jiteshwar Mahto', 400, true),
  ('Jugesh Mahto', 400, true),
  ('Kadir Khan', 500, true),
  ('Kalim Painer', 700, true),
  ('Kamdev Usra', 400, true),
  ('Kamlesh Ravi', 550, true),
  ('Kanchan Binod', 450, true),
  ('karan', 500, true),
  ('Karan Rajwar 3', 400, true),
  ('Kartik Rajwar', 400, true),
  ('Krish Kumar', 400, true),
  ('Krish Mahto', 400, true),
  ('Krishna Painter', 500, true),
  ('Kundan', 500, true),
  ('Kundan Balsagra', 400, true),
  ('Lallan rajwar', 450, true),
  ('Laxman', 450, true),
  ('Mahesh Mahto', 400, true),
  ('Mahesh Rajwar', 500, true),
  ('Manish Karmali', 400, true),
  ('Manish Rajwar', 400, true),
  ('Manish Ravidas', 450, true),
  ('Manoj Delhi', 1200, true),
  ('Manoj Rajwar', 450, true),
  ('Marshal', 450, true),
  ('Md ali', 650, true),
  ('Md Arbaz', 400, true),
  ('Md Rishu', 400, true),
  ('Meghnath', 550, true),
  ('Mithilesh Usra', 400, true),
  ('Mithlesh', 650, true),
  ('Mithun Rajwar', 450, true),
  ('Mithun Saw', 400, true),
  ('Mithun Usra', 400, true),
  ('Mohit Kumar', 400, true),
  ('Mohit Kumar 2', 400, true),
  ('Monty', 400, true),
  ('Mukesh Kumar', 400, true),
  ('Munna', 450, true),
  ('Munna Katihar', 600, true),
  ('Nakul Karmali', 400, true),
  ('Naresh', 400, true),
  ('Naveen Fitter', 500, true),
  ('Navin Labour', 500, true),
  ('Nikhil Kumar', 400, true),
  ('Nikhil Rajwar', 400, true),
  ('Nikhil Ranabhatt', 400, true),
  ('Nikhlesh Gola', 500, true),
  ('Nitish', 450, true),
  ('Nitish Paswan', 400, true),
  ('Omnath', 500, true),
  ('Pankaj Karmali', 500, true),
  ('Pankaj Saw', 500, true),
  ('Pankaj Staff', 650, true),
  ('Pappu', 450, true),
  ('Pappu Mistri', 650, true),
  ('Pappu Ram', 400, true),
  ('Pawan Bediya', 400, true),
  ('Pawan Kumar', 400, true),
  ('Pintu Nawadih', 400, true),
  ('Piyush', 450, true),
  ('Prabhu', 400, true),
  ('Pradeep Giri', 400, true),
  ('Prakash', 500, true),
  ('Prakash Usra', 400, true),
  ('Pramod Ram', 400, true),
  ('Prem karmali', 500, true),
  ('Prem Kumar', 400, true),
  ('Prem Rajwar', 400, true),
  ('Punit Usra', 450, true),
  ('Pyarelal Rajwar', 400, true),
  ('Rahul Karmali', 600, true),
  ('Rahul Munda', 400, true),
  ('Rahul Rajwar', 550, true),
  ('Rahul Uswadih', 450, true),
  ('Raj Karmali', 400, true),
  ('Raj Kumar Usra', 500, true),
  ('Raja Kumar', 400, true),
  ('Rajdev', 500, true),
  ('Rajendra Kumar', 400, true),
  ('Rajendra Munda', 400, true),
  ('Raju Balsagra', 400, true),
  ('Raju Karmali', 400, true),
  ('Raju karmali 2', 400, true),
  ('Raju Rajwar', 400, true),
  ('Rakesh Katihar', 600, true),
  ('Rakesh Munda', 400, true),
  ('Ram Katihar', 600, true),
  ('Ranjan Mahto', 400, true),
  ('Ranjeet fitter', 550, true),
  ('Ranjit Mahto Usra', 500, true),
  ('Raushan Bedia', 400, true),
  ('Raushan Soso', 400, true),
  ('Raushan Usra', 400, true),
  ('Ravi Kaitha', 400, true),
  ('Ravi kr Ram', 400, true),
  ('Ravi Usra', 400, true),
  ('Ridan', 500, true),
  ('Rishu Rajwar', 400, true),
  ('Ritesh Rajwar', 400, true),
  ('Ritik', 500, true),
  ('Ritik Mile', 400, true),
  ('Ritik Petarwar', 400, true),
  ('Rohan Karmali', 400, true),
  ('Rohit Keshri', 400, true),
  ('Rohit Rajwar', 400, true),
  ('Rohit Singh welder', 450, true),
  ('Roshan Katihar', 400, true),
  ('Sachin Katihar', 600, true),
  ('Sachin Kumar', 450, true),
  ('Saddab', 700, true),
  ('Sagar', 550, true),
  ('Sagar Bedia', 400, true),
  ('Sagar Mahto', 400, true),
  ('Sagar Paswan', 400, true),
  ('Sagar Rajwar', 450, true),
  ('Sahil', 700, true),
  ('Sahil Kumar', 400, true),
  ('Sahil Thapa', 400, true),
  ('Sajan fitter', 500, true),
  ('Sajan Ram', 400, true),
  ('Sameer kr Das', 450, true),
  ('Sameer Rajwar', 400, true),
  ('Sandeep Mahto', 400, true),
  ('Sanjay Fitter', 550, true),
  ('Sanjay Katihar', 600, true),
  ('Sanoj Kaitha', 400, true),
  ('Santosh Staff', 650, true),
  ('Satish Nayak', 400, true),
  ('Shankar', 450, true),
  ('Shankar Das', 1200, true),
  ('Shankar Kaitha', 400, true),
  ('Shankar Kumar Mahto', 400, true),
  ('Shekhar Rajwar', 450, true),
  ('Shiv Charan', 400, true),
  ('Shivam Rajwar', 400, true),
  ('Shivnath Manjhi', 450, true),
  ('Shubham', 550, true),
  ('Shyam Katihar', 600, true),
  ('Shyam Kumar', 400, true),
  ('Shyam Mahto', 400, true),
  ('Sikandar', 450, true),
  ('Simpu Rajwar', 400, true),
  ('Sonu Ansari', 500, true),
  ('Sonu Ram', 400, true),
  ('Subhash Kumar', 450, true),
  ('Sudhir Katihar', 600, true),
  ('Sujeet Das', 400, true),
  ('Sultan', 750, true),
  ('Sumeet Rajwar', 400, true),
  ('Sumit Katihar', 450, true),
  ('Sumit welder', 450, true),
  ('Sunil Balsagra', 400, true),
  ('Sunil Karmali', 500, true),
  ('Sunil Soren', 400, true),
  ('Sunny Rajwar', 400, true),
  ('Suraj Karmali', 400, true),
  ('Suraj Mahto', 400, true),
  ('Suraj Rajwar', 400, true),
  ('Suraj Soren', 400, true),
  ('Suraj Soren 2', 450, true),
  ('Surendar fitter', 800, true),
  ('Sushant Munda', 400, true),
  ('Sushant Rajwar', 400, true),
  ('Sushil Mistri', 962, true),
  ('Tapeshwar Mahto', 400, true),
  ('Tarun Rajwar', 500, true),
  ('Tarzan labour', 550, true),
  ('Tarzon 2', 450, true),
  ('Tipu', 800, true),
  ('Tonny', 500, true),
  ('Uday', 600, true),
  ('Umesh Karmali', 400, true),
  ('Umesh Kumar', 400, true),
  ('Umesh Mahto', 400, true),
  ('Uttam Rajwar', 450, true),
  ('Vicky', 550, true),
  ('Vicky 3', 400, true),
  ('Vicky Munda', 400, true),
  ('Vicky Rajwar', 400, true),
  ('Vicky Rajwar 2', 450, true),
  ('Vijay Kumar', 450, true),
  ('Vijay Mahto', 400, true),
  ('Vijay Usra', 400, true),
  ('Vikas', 600, true),
  ('Vikash mahto', 500, true),
  ('Vikash Manoj Delhi', 650, true),
  ('Vikash Munda', 400, true),
  ('Vimlesh Kumar', 400, true),
  ('Vinay Mahto', 400, true),
  ('Vishal Bediya', 400, true),
  ('Vishal Kumar', 450, true),
  ('Vishal Mahto', 400, true),
  ('Vivek Kumar', 400, true),
  ('ABHAY USRA', 400, true),
  ('AJEET KATIHAR', 500, true),
  ('ANIL KR MUNDA', 400, true),
  ('ANKIT MUNDA', 400, true),
  ('ARJUN BONGABAR', 400, true),
  ('BABLU KARMALI', 400, true),
  ('BADAL BONGABAR', 400, true),
  ('BADAL KR KAITHA', 400, true),
  ('BHANU PRATAP', 400, true),
  ('BHIM KARMALI', 400, true),
  ('BHOLA KARMALI', 400, true),
  ('CHANDAN RAJWAR', 400, true),
  ('DEEPAK LABOUR', 500, true),
  ('DEVNARAYAN MAHTO', 400, true),
  ('GOLU VERMA', 400, true),
  ('JASWANT KARMALI', 400, true),
  ('KARAMVEER', 400, true),
  ('KRISHNA KUMAR', 400, true),
  ('KRISHNA RAM', 400, true),
  ('LALO MAHTO', 400, true),
  ('MAHENDRA BODRA', 400, true),
  ('MAHENDRA RAJWAR', 400, true),
  ('MANAV RAJ', 400, true),
  ('MANNU KATIHAR', 400, true),
  ('MANTU RAJWAR', 400, true),
  ('MITHLESH KARMALI', 400, true),
  ('MITHLESH PHUSRO', 400, true),
  ('MOHIT GOPE', 400, true),
  ('MOTU RAJWAR', 400, true),
  ('MUNNA RAJWAR', 400, true),
  ('MURTI RAJ', 400, true),
  ('NIRANJAN RAJWAR', 400, true),
  ('NITESH KARMALI', 400, true),
  ('PAPPU BARWATAD', 400, true),
  ('PAPPU KARMALI (2 DAYS 8+5)', 400, true),
  ('PAPPU KARMALI', 400, true),
  ('PAWAN RAM', 400, true),
  ('PRADEEP RAM', 400, true),
  ('RAJESH KARMALI', 400, true),
  ('RAM PRAKASH MANJHI', 400, true),
  ('RANDHIR  ORAON', 400, true),
  ('RAUSHAN BARWATAD', 400, true),
  ('RAVI BEDIA', 400, true),
  ('RAVINDRA BASKE', 400, true),
  ('RITESH USRA', 400, true),
  ('RITIK BARWATAD', 400, true),
  ('ROHAN SINGH', 400, true),
  ('SACHIN BARWATAD', 400, true),
  ('SACHIN KARMALI', 400, true),
  ('SAGAR USRA', 400, true),
  ('SAMEER MAHTO', 400, true),
  ('SAMEER RAJWANSHI', 400, true),
  ('SANJAY RAJWAR', 400, true),
  ('SANTOSH KARMALI', 400, true),
  ('SHEKHAR', 400, true),
  ('SIKANDAR MUNDA', 400, true),
  ('SOMRA KARMALI', 400, true),
  ('SONU TUDU', 400, true),
  ('SUMEET KATIHAR', 600, true),
  ('SUNIL HEMBROM', 400, true),
  ('SUNIL RAJWAR', 400, true),
  ('SUNNY KARMALI', 400, true),
  ('SURAJ KR LOLO', 400, true),
  ('SUREN RAJWAR', 400, true),
  ('UMESH BALSAGRA', 400, true),
  ('UMESH LOLO', 400, true),
  ('UTTAM MAHTO', 400, true),
  ('VIKASH RAJWAR', 400, true)
ON CONFLICT (name) DO UPDATE SET daily_rate = EXCLUDED.daily_rate;
